# Kamal deployment configuration for Surya's Cookware
service: suryas-cookware
image: desinghrajan/suryas-cookware

# Servers
servers:
  web:
    hosts:
      - 139.84.156.199
    labels:
      traefik.http.routers.suryas-cookware.rule: Host(`suryascookware.com`) || Host(`www.suryascookware.com`)
      traefik.http.routers.suryas-cookware.entrypoints: websecure
      traefik.http.routers.suryas-cookware.tls: true
      traefik.http.routers.suryas-cookware.tls.certresolver: letsencrypt

# Registry
registry:
  username: desinghrajan
  password:
    - KAMAL_REGISTRY_PASSWORD

# Proxy
proxy:
  ssl: true
  host: suryascookware.com,www.suryascookware.com
  app_port: 3000
  healthcheck:
    path: /
    timeout: 60
    interval: 10

# Environment
env:
  clear:
    NODE_ENV: production

# SSH
ssh:
  user: root

# Builder
builder:
  arch: amd64
